sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        c7Vckg3LZWfchtuc1g2tSzwRI/+rkhoyz2N8liXLTuz8jKPBXnrhC30FHH13gaGwHSE9g5at2gOvNvBnb1/CDei3zSjk6ueBYlQmW875bjsV7vZL9FN3E6MJcWA1YtbXKGWAOv8glgniKdEEpu/IivVjiwoOCOE5m3inm4E3EvCv7n4DKWK/R2+ui3cZTh7SLlAy9IulA1mdOE0YgIeg4AiJx2E4heJb3t9ynNx5KNQZZZAPPfaZyBEWp7/cADjMwiHRYAqx6/9mHYiFJj9SKpu1ETGijrIcR7Cw6mhBmVDVvjSHHcFyzQcGoLpc8mpBsuOD6/UjlptYfQGy1LPM297Hhhf5a+EryGv3tp9odvSC5hDk248jUzRD2sHhJGowpJzbIdK41MFm1eNLdY9AKXhtO1W2rPVewkKc0l7BTa4tKV/lFuNZ29WrzUEdQQ1TRj3hfn+z+prazyeCVSZ+3tSYD7vW9leDoBsRFz7OFognz4wK9BNPVU4NX7lH3HVvN04blt86oqhlUhIWdzu+43AkVn5Y96uPjLX8Mq3YRt5xVeD1O5h3+uBjKMWWV9+ncX6Ju0hVShMg15UtPe+sxRnIOY0wmlvIVd5wVKwfQxX+28MLitg7yOtwzHm+SFdz5LJFXB2oIf8K02Bj9B7IJ3Md6m4XUJNLVnIjD33coTU=
    - secure: >-
        F+2ADouULcm14GFQu0w5MGclQZL45qtr7uIro2xvDGw++1APGUMlZrOM8cw/rq5Noz9cLGhunOErTlWNkMdh3OfdnFaWxOSV6xq4qRzkwTe3eP4VFQokaqhKEOI+4S//z705usaOE7dtVFOQBcd/YZ1zM8bsgimC/+jF4Ru2b2XAEQG4hFx8argdXTDVgi2ycBr4njmE6r5dSK9GJO5kpCqaHPIgY0JWmje4fp+xHHebi6YUFCr+/UFGTYdEe9EjXLLYTZveQ7Dc2VYetnKG1arZF4YKoQItCgjDODdDKUPpsfWP5q1pcfRXRKCSDfsLMUrEYn2wdodapQq57aoZYiBgT/8l2chHWJCCks7Bf3XW5hNypepqAJ7yBYUXvgD8N20Zt885Kk9DdY1CFViXvmytmV66o+MGWMXWDIj10e0F9pnNtaBGHLG+iXfNMAwOYWwKRmzYwbQDROh0kASxAA+K15tepFDVoPssADoimCE4nk7ApC6wCUohZNOiENM84st+MGGSQ5s3GHwTz/+zIL6WwsZ/RC1q03AzwCVbZX/yVC9uw2JFVjkPNGb2llEAKaT4uaxVFCpgEsxsDrP2IF6oq/aLsnnMacUv9Tr5i0VnVKlf+me/dSczpcvs+/afRgNPMQvD87/2ZtjRg9AuG8YrDNW2QgRF9tIxjIBcIVU=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
